language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 LEVELDB_VERSION=caad1b40f484b4c636d6c44db759db14475af4bb

before_script:
 - sudo apt-get update -qq
 - sudo apt-get install valgrind -qq
 - sh travis/prepare.sh

script: sh travis/run-test.sh

cache:
 directories:
  - leveldb-$LEVELDB_VERSION

#notifications:
#  email:
#    - reeze.xia@gmail.com
